# Generated by Django 4.2.11 on 2024-04-08 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nom_du_pasteur_du_groupe', models.CharField(max_length=200)),
                ('nom_du_superviseur_des_jeunes', models.CharField(max_length=100)),
                ('nom_du_superviseur_adjoin_des_jeunes', models.CharField(max_length=100)),
                ('nombre_de_membres', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nom_du_pasteur_regional', models.CharField(max_length=200)),
                ('nombre_de_membres', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_du_pasteur', models.CharField(max_length=100)),
                ('nom_du_pasteur_adjoin', models.CharField(max_length=100)),
                ('nom_du_dirigeant_des_jeunes', models.CharField(max_length=100)),
                ('nom_du_dirigeant_adjoin_des_jeunes', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, max_length=250)),
                ('nombre_de_membres', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('bp', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/header')),
                ('body_image', models.ImageField(blank=True, null=True, upload_to='images/Body')),
                ('body_image1', models.ImageField(blank=True, null=True, upload_to='images/Body')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
