# Generated by Django 4.2.11 on 2024-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eglise',
            name='nom_du_dirigeant_adjoin_des_enfants',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='nom_du_dirigeant_des_enfants',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
