# Generated by Django 4.2.11 on 2024-07-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0002_eglise_nom_du_dirigeant_adjoin_des_enfants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='nom_du_dirigeant_adjoin_des_jeunes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='nom_du_dirigeant_des_jeunes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='nom_du_pasteur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='nom_du_pasteur_adjoin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
