# Generated by Django 4.2.11 on 2024-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0003_alter_eglise_nom_du_dirigeant_adjoin_des_jeunes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='nombre_de_membres',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eglise',
            name='telephone',
            field=models.IntegerField(blank=True),
        ),
    ]
