# Generated by Django 4.2.11 on 2024-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0004_alter_eglise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='nombre_de_membres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
