# Generated by Django 4.2.11 on 2024-07-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0005_alter_eglise_nombre_de_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eglise',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
