# Generated by Django 6.0.2 on 2026-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eglise',
            name='nom_du_dirigeant_adjoin_des_enfants',
        ),
        migrations.RemoveField(
            model_name='eglise',
            name='nom_du_dirigeant_adjoin_des_jeunes',
        ),
        migrations.RemoveField(
            model_name='eglise',
            name='nom_du_pasteur_adjoin',
        ),
        migrations.AddField(
            model_name='eglise',
            name='coordinatrice_des_femmes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='dirigeant_de_zone1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='dirigeant_de_zone2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_des_femmes1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_des_femmes2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_des_jeunes_femme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eglise',
            name='responsable_des_jeunes_professionnel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
