# Generated by Django 6.0.2 on 2026-04-09 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adultes', '0004_alter_adulte_description_sur_vous_et_votre_famille'),
        ('Eglises', '0006_alter_eglise_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type de Contribution',
                'verbose_name_plural': 'Types de Contribution',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_objectif', models.PositiveIntegerField(blank=True, help_text='Facultatif — si renseigné, le restant sera calculé automatiquement', null=True, verbose_name='Montant objectif (FCFA)')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('date_contribution', models.DateField(verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_saisies', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='Eglises.eglise', verbose_name='Église (District)')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='Adultes.adulte', verbose_name='Membre')),
                ('type_contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='Voeux.typecontribution', verbose_name='Type de contribution')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-date_contribution'],
            },
        ),
        migrations.CreateModel(
            name='VersementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField(verbose_name='Date du versement')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='Voeux.contribution')),
            ],
            options={
                'verbose_name': 'Versement Contribution',
                'verbose_name_plural': 'Versements Contributions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Voeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_promis', models.PositiveIntegerField(verbose_name='Montant promis (FCFA)')),
                ('details', models.TextField(blank=True, verbose_name='Détails / Objet du voeu')),
                ('date_voeu', models.DateField(verbose_name='Date du voeu')),
                ('premier_versement', models.PositiveIntegerField(default=0, help_text='Facultatif — laisser 0 si pas de versement immédiat', verbose_name='Premier versement (FCFA)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voeux_saisis', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to='Eglises.eglise', verbose_name='Église (District)')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to='Adultes.adulte', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Voeu',
                'verbose_name_plural': 'Voeux',
                'ordering': ['-date_voeu'],
            },
        ),
        migrations.CreateModel(
            name='VersementVoeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField(verbose_name='Date du versement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='Voeux.voeu')),
            ],
            options={
                'verbose_name': 'Versement Voeu',
                'verbose_name_plural': 'Versements Voeux',
                'ordering': ['-date'],
            },
        ),
    ]
