# Generated by Django 6.0.2 on 2026-04-10 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voeux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_montant', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancien montant objectif (FCFA)')),
                ('nouveau_montant', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nouveau montant objectif (FCFA)')),
                ('justification', models.TextField(verbose_name='Justification de la modification')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_contributions', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='Voeux.contribution')),
            ],
            options={
                'verbose_name': 'Historique modification Contribution',
                'verbose_name_plural': 'Historiques modifications Contributions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueVoeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_montant', models.PositiveIntegerField(verbose_name='Ancien montant (FCFA)')),
                ('nouveau_montant', models.PositiveIntegerField(verbose_name='Nouveau montant (FCFA)')),
                ('justification', models.TextField(verbose_name='Justification de la modification')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_voeux', to=settings.AUTH_USER_MODEL)),
                ('voeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='Voeux.voeu')),
            ],
            options={
                'verbose_name': 'Historique modification Voeu',
                'verbose_name_plural': 'Historiques modifications Voeux',
                'ordering': ['-created'],
            },
        ),
    ]
