# Generated by Django 6.0.2 on 2026-04-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voeux', '0002_historiques_montants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueVersementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_montant', models.PositiveIntegerField(verbose_name='Ancien montant (FCFA)')),
                ('nouveau_montant', models.PositiveIntegerField(verbose_name='Nouveau montant (FCFA)')),
                ('justification', models.TextField(verbose_name='Justification de la correction')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_versements_contributions', to=settings.AUTH_USER_MODEL)),
                ('versement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='Voeux.versementcontribution')),
            ],
            options={
                'verbose_name': 'Historique correction Versement Contribution',
                'verbose_name_plural': 'Historiques corrections Versements Contributions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueVersementVoeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_montant', models.PositiveIntegerField(verbose_name='Ancien montant (FCFA)')),
                ('nouveau_montant', models.PositiveIntegerField(verbose_name='Nouveau montant (FCFA)')),
                ('justification', models.TextField(verbose_name='Justification de la correction')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_versements_voeux', to=settings.AUTH_USER_MODEL)),
                ('versement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='Voeux.versementvoeu')),
            ],
            options={
                'verbose_name': 'Historique correction Versement Voeu',
                'verbose_name_plural': 'Historiques corrections Versements Voeux',
                'ordering': ['-created'],
            },
        ),
    ]
