# Generated by Django 4.2.11 on 2024-04-08 11:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eglises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(max_length=150)),
                ('lieu_de_naissance', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=150)),
                ('status_matrimoniale', models.CharField(blank=True, max_length=150)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=25)),
                ('rhesus', models.CharField(blank=True, max_length=10)),
                ('role_dans_leglise', models.CharField(blank=True, max_length=70)),
                ('occupation', models.CharField(blank=True, max_length=70)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=150, null=True)),
                ('annee_de_conversion', models.CharField(blank=True, max_length=150)),
                ('baptiser', models.CharField(blank=True, max_length=150)),
                ('annee_de_bapteme', models.CharField(blank=True, max_length=150)),
                ('nombre_d_enfant', models.CharField(blank=True, max_length=150)),
                ('description_sur_vous_et_votre_famille', ckeditor.fields.RichTextField(blank=True)),
                ('adulte_image', models.ImageField(blank=True, null=True, upload_to='images/adulte')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
            ],
        ),
    ]
