# Generated by Django 4.2.11 on 2024-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adultes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adulte',
            name='occupation',
        ),
    ]
