# Generated by Django 4.2.11 on 2024-04-10 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adultes', '0002_remove_adulte_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adulte',
            name='description_sur_vous_et_votre_famille',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
