# Generated by Django 4.2.11 on 2024-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adultes', '0003_alter_adulte_description_sur_vous_et_votre_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adulte',
            name='description_sur_vous_et_votre_famille',
            field=models.TextField(blank=True),
        ),
    ]
