# Generated by Django 4.2.11 on 2024-04-08 11:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eglises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(max_length=150)),
                ('lieu_de_naissance', models.CharField(blank=True, max_length=150)),
                ('classe', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=150)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=25)),
                ('rhesus', models.CharField(blank=True, max_length=10)),
                ('talents_de_l_enfant', models.CharField(blank=True, max_length=400, null=True)),
                ('avec_qui_vit_il', models.CharField(blank=True, max_length=100)),
                ('nombre_de_freres', models.IntegerField(blank=True)),
                ('les_freres_sont_ils_dans_leglise', models.CharField(blank=True, max_length=100)),
                ('nom_des_freres', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_de_soeurs', models.IntegerField(blank=True)),
                ('les_soeurs_sont_elles_dans_leglise', models.CharField(blank=True, max_length=100)),
                ('nom_des_soeurs', models.CharField(blank=True, max_length=500, null=True)),
                ('nom_des_parentes', models.CharField(blank=True, max_length=400)),
                ('les_parents_sont_ils_dans_leglise', models.CharField(blank=True, max_length=100)),
                ('nom_des_parents_ou_tuteurs', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('description_sur_l_enfant', ckeditor.fields.RichTextField(blank=True)),
                ('enfant_image', models.ImageField(blank=True, null=True, upload_to='images/enfants')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
            ],
        ),
    ]
