# Generated by Django 4.2.11 on 2024-04-10 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enfants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='description_sur_l_enfant',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
