# Generated by Django 4.2.11 on 2024-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enfants', '0002_alter_enfant_description_sur_l_enfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='description_sur_l_enfant',
            field=models.TextField(blank=True),
        ),
    ]
