# Generated by Django 4.2.11 on 2024-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enfants', '0003_alter_enfant_description_sur_l_enfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='talents_de_l_enfant',
            field=models.CharField(blank=True, default=1, max_length=400),
            preserve_default=False,
        ),
    ]
