# Generated by Django 4.2.11 on 2024-06-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0001_initial'),
        ('Enfants', '0004_alter_enfant_talents_de_l_enfant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eglises.region'),
            preserve_default=False,
        ),
    ]
