# Generated by Django 4.2.11 on 2024-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('telephone', models.IntegerField(blank=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('telephone', models.IntegerField(blank=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
            ],
        ),
    ]
