# Generated by Django 4.2.11 on 2024-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LumiereCite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='probleme_particulier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='projets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
