# Generated by Django 4.2.11 on 2024-07-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LumiereCite', '0002_etablissement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
