# Generated by Django 4.2.11 on 2024-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LumiereCite', '0003_remove_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='groupe_titulaire',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='region',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
