# Generated by Django 4.2.11 on 2022-01-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bilans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellules',
            name='billan_de_la_cellule',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evenementspecial',
            name='billan_de_l_evenement',
            field=models.TextField(),
        ),
    ]
