# Generated by Django 4.2.11 on 2024-07-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0001_initial'),
        ('Bilans', '0002_alter_cellules_billan_de_la_cellule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementspecial',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise'),
            preserve_default=False,
        ),
    ]
