# Generated by Django 6.0.2 on 2026-04-18 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0007_remove_eglise_nom_du_dirigeant_adjoin_des_enfants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersementQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('photo_recu', models.ImageField(blank=True, null=True, upload_to='images/quotas/')),
                ('description', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_quota', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_quota', to='Eglises.eglise')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QuotaEglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('annee', models.IntegerField(default=2025)),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas_eglise', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='Eglises.eglise')),
            ],
            options={
                'ordering': ['eglise__groupe', 'eglise__nom'],
                'unique_together': {('eglise', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='QuotaGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('annee', models.IntegerField(default=2025)),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['region', 'groupe'],
                'unique_together': {('groupe', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='QuotaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('annee', models.IntegerField(default=2025)),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['region'],
                'unique_together': {('region', 'annee')},
            },
        ),
    ]
