# Generated by Django 6.0.2 on 2026-04-19 15:46

import Quotas.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotaeglise',
            name='annee',
            field=models.IntegerField(default=Quotas.models.annee_courante),
        ),
        migrations.AlterField(
            model_name='quotagroupe',
            name='annee',
            field=models.IntegerField(default=Quotas.models.annee_courante),
        ),
        migrations.AlterField(
            model_name='quotaregion',
            name='annee',
            field=models.IntegerField(default=Quotas.models.annee_courante),
        ),
        migrations.CreateModel(
            name='PromesseQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_membre', models.CharField(max_length=150)),
                ('montant_promis', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé')], default='ATTENTE', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('quota_eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promesses', to='Quotas.quotaeglise')),
            ],
            options={
                'ordering': ['nom_membre'],
            },
        ),
    ]
