# Generated by Django 6.0.2 on 2026-04-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_retraite', models.CharField(choices=[('DECEMBRE', 'Retraite de Décembre'), ('PAQUES', 'Retraite de Pâques')], max_length=20, verbose_name='Type de retraite')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('theme', models.CharField(blank=True, max_length=300, verbose_name='Thème')),
                ('adultes_h', models.PositiveIntegerField(default=0, verbose_name='Adultes (H)')),
                ('adultes_f', models.PositiveIntegerField(default=0, verbose_name='Adultes (F)')),
                ('jeunes_h', models.PositiveIntegerField(default=0, verbose_name='Jeunes (H)')),
                ('jeunes_f', models.PositiveIntegerField(default=0, verbose_name='Jeunes (F)')),
                ('enfants', models.PositiveIntegerField(default=0, verbose_name='Enfants')),
                ('nouveaux_convertis', models.PositiveIntegerField(default=0, verbose_name='Nouveaux convertis')),
                ('nombre_eglises', models.PositiveIntegerField(default=0, help_text='Nombre de districts/églises ayant participé', verbose_name="Nb. d'églises représentées")),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraites_saisies', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraites', to='Eglises.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Retraite',
                'verbose_name_plural': 'Retraites',
                'ordering': ['-annee', 'type_retraite', 'region__name'],
                'unique_together': {('type_retraite', 'region', 'annee')},
            },
        ),
    ]
