# Generated by Django 6.0.2 on 2026-04-11 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retraites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retraite',
            name='adultes_f',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='adultes_h',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='enfants',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='jeunes_f',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='jeunes_h',
        ),
        migrations.RemoveField(
            model_name='retraite',
            name='nouveaux_convertis',
        ),
        migrations.AlterField(
            model_name='retraite',
            name='nombre_eglises',
            field=models.PositiveIntegerField(default=0, help_text='Nombre total de districts/églises ayant participé', verbose_name="Nb. d'églises représentées"),
        ),
        migrations.AlterField(
            model_name='retraite',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observations générales'),
        ),
        migrations.CreateModel(
            name='JourRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du jour')),
                ('adultes_h', models.PositiveIntegerField(default=0, verbose_name='Adultes (H)')),
                ('adultes_f', models.PositiveIntegerField(default=0, verbose_name='Adultes (F)')),
                ('jeunes_h', models.PositiveIntegerField(default=0, verbose_name='Jeunes (H)')),
                ('jeunes_f', models.PositiveIntegerField(default=0, verbose_name='Jeunes (F)')),
                ('enfants', models.PositiveIntegerField(default=0, verbose_name='Enfants')),
                ('nouveaux_convertis', models.PositiveIntegerField(default=0, verbose_name='Nouveaux convertis')),
                ('notes_jour', models.TextField(blank=True, verbose_name='Observations du jour')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_jours_retraite', to=settings.AUTH_USER_MODEL)),
                ('retraite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='Retraites.retraite', verbose_name='Retraite')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'ordering': ['date'],
                'unique_together': {('retraite', 'date')},
            },
        ),
    ]
