# Generated by Django 4.2.11 on 2024-07-23 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eglises', '0006_alter_eglise_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Lundi', 'Lundi'), ('Jeudi', 'Jeudi'), ('Dimanche', 'Dimanche')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultes_hommes', models.IntegerField(default=0)),
                ('adultes_femmes', models.IntegerField(default=0)),
                ('jeunes_garcons', models.IntegerField(default=0)),
                ('jeunes_filles', models.IntegerField(default=0)),
                ('enfants_garcons', models.IntegerField(default=0)),
                ('enfants_filles', models.IntegerField(default=0)),
                ('cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seances.seance')),
            ],
        ),
    ]
