# Generated by Django 4.2.11 on 2024-07-23 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Seances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='date',
        ),
        migrations.AddField(
            model_name='bilan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seance',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
