# Generated by Django 4.2.11 on 2024-07-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seances', '0002_remove_seance_date_bilan_date_alter_seance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bilan',
            options={'ordering': ['-add_date']},
        ),
    ]
