# Generated by Django 6.0.2 on 2026-04-07 00:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        ('Seances', '0003_alter_bilan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bilan',
            unique_together={('eglise', 'seance', 'date')},
        ),
        migrations.CreateModel(
            name='HistoricalBilan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('adultes_hommes', models.IntegerField(default=0)),
                ('adultes_femmes', models.IntegerField(default=0)),
                ('jeunes_garcons', models.IntegerField(default=0)),
                ('jeunes_filles', models.IntegerField(default=0)),
                ('enfants_garcons', models.IntegerField(default=0)),
                ('enfants_filles', models.IntegerField(default=0)),
                ('cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('add_date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auteur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Eglises.eglise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Seances.seance')),
            ],
            options={
                'verbose_name': 'historical bilan',
                'verbose_name_plural': 'historical bilans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
