# Generated by Django 6.0.2 on 2026-03-26 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(choices=[('REGION', 'Région (Grand Lomé)'), ('GROUPE', 'Groupe'), ('DISTRICT', 'District (Église locale)'), ('ADMIN', 'Administrateur Global')], default='DISTRICT', max_length=20)),
                ('region_assignee', models.CharField(blank=True, help_text='Nom exact de la Région si niveau = REGION', max_length=100, null=True)),
                ('groupe_assigne', models.CharField(blank=True, help_text='Nom exact du Groupe si niveau = GROUPE', max_length=100, null=True)),
                ('district_assigne', models.CharField(blank=True, help_text='Nom exact du District/Église si niveau = DISTRICT', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
