# Generated by Django 6.0.2 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='section_assignee',
            field=models.CharField(choices=[('TOUS', 'Toutes les sections (Pasteur/Admin)'), ('ADULTES', 'Section Adultes'), ('JEUNES', 'Section Jeunes'), ('ENFANTS', 'Section Enfants')], default='TOUS', help_text="Restreindre l'accès à une section spécifique au sein de l'église", max_length=20),
        ),
    ]
