# Generated by Django 6.0.2 on 2026-04-07 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanGCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la croisade GCK')),
                ('hommes', models.PositiveIntegerField(default=0)),
                ('femmes', models.PositiveIntegerField(default=0)),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('nouveaux_convertis', models.PositiveIntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('difficultes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_gck', to='Eglises.eglise')),
            ],
            options={
                'verbose_name': 'Bilan GCK',
                'verbose_name_plural': 'Bilans GCK',
                'ordering': ['-date'],
            },
        ),
    ]
