# Generated by Django 6.0.2 on 2026-04-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        ('GCK', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bilangck',
            unique_together={('eglise', 'date')},
        ),
    ]
