# Generated by Django 6.0.2 on 2026-04-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        ('GCK', '0003_bilangck_adultes_jeunes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanConferenceMinistres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la conférence (matin GCK)')),
                ('adultes_hommes', models.PositiveIntegerField(default=0, verbose_name='Adultes Hommes')),
                ('adultes_femmes', models.PositiveIntegerField(default=0, verbose_name='Adultes Femmes')),
                ('jeunes_hommes', models.PositiveIntegerField(default=0, verbose_name='Jeunes Hommes')),
                ('jeunes_femmes', models.PositiveIntegerField(default=0, verbose_name='Jeunes Femmes')),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('nouveaux_convertis', models.PositiveIntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('difficultes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_conference', to='Eglises.eglise')),
            ],
            options={
                'verbose_name': 'Bilan Conférence des Ministres',
                'verbose_name_plural': 'Bilans Conférence des Ministres',
                'ordering': ['-date'],
                'unique_together': {('eglise', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BilanImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du samedi Impact (GCK)')),
                ('adultes_hommes', models.PositiveIntegerField(default=0, verbose_name='Adultes Hommes')),
                ('adultes_femmes', models.PositiveIntegerField(default=0, verbose_name='Adultes Femmes')),
                ('jeunes_hommes', models.PositiveIntegerField(default=0, verbose_name='Jeunes Hommes')),
                ('jeunes_femmes', models.PositiveIntegerField(default=0, verbose_name='Jeunes Femmes')),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('nouveaux_convertis', models.PositiveIntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('difficultes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_impact', to='Eglises.eglise')),
            ],
            options={
                'verbose_name': "Bilan Académie d'Impact",
                'verbose_name_plural': "Bilans Académie d'Impact",
                'ordering': ['-date'],
                'unique_together': {('eglise', 'date')},
            },
        ),
    ]
