# Generated by Django 6.0.2 on 2026-04-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCK', '0004_add_conference_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilangck',
            name='quete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Quête (FCFA)'),
        ),
    ]
