# Generated by Django 4.2.11 on 2024-06-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(blank=True)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=25)),
                ('rhesus', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('role_dans_leglise', models.CharField(blank=True, max_length=70)),
                ('talents_du_jeune', models.CharField(blank=True, max_length=400, null=True)),
                ('avec_qui_vit_il', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_de_freres', models.IntegerField(blank=True, null=True)),
                ('les_freres_sont_ils_dans_leglise', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_des_freres', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_de_soeurs', models.IntegerField(blank=True, null=True)),
                ('les_soeurs_sont_elles_dans_leglise', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_des_soeurs', models.CharField(blank=True, max_length=500, null=True)),
                ('nom_des_parents', models.CharField(max_length=400)),
                ('les_parents_sont_ils_dans_leglise', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_de_telephone_des_parents_ou_tuteurs', models.IntegerField(blank=True, null=True)),
                ('classe_ou_niveau_d_etude', models.CharField(blank=True, max_length=200, null=True)),
                ('Faculte_ou_domaine_d_emploie', models.CharField(blank=True, max_length=200, null=True)),
                ('jeune_image', models.ImageField(blank=True, null=True, upload_to='images/jeunes')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eglises.region')),
            ],
        ),
    ]
