# Generated by Django 4.2.11 on 2024-07-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jeunes_app', '0002_remove_jeune_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeune',
            name='annee_de_bapteme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jeune',
            name='annee_de_conversion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jeune',
            name='baptiser',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
