# Generated by Django 4.2.11 on 2024-06-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
