# Generated by Django 6.0.2 on 2026-03-27 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0006_alter_eglise_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Dîmes Janvier 2026, Achat Matériel', max_length=200)),
                ('type_transaction', models.CharField(choices=[('ENTREE', 'Entrée (Recette)'), ('SORTIE', 'Sortie (Dépense)')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eglises.eglise')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
