# Generated by Django 6.0.2 on 2026-04-18 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0007_remove_eglise_nom_du_dirigeant_adjoin_des_enfants_and_more'),
        ('Finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('photo_recu', models.ImageField(blank=True, null=True, upload_to='images/versements/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='Eglises.eglise')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
