# Generated by Django 6.0.2 on 2026-04-18 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eglises', '0007_remove_eglise_nom_du_dirigeant_adjoin_des_enfants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NouveauVenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('H', 'Homme / Garçon'), ('F', 'Femme / Fille')], max_length=1)),
                ('categorie', models.CharField(choices=[('ADULTE', 'Adulte'), ('JEUNE', 'Jeune'), ('ENFANT', 'Enfant')], default='ADULTE', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('date_venue', models.DateField(default=django.utils.timezone.now)),
                ('origine', models.CharField(choices=[('INVITATION', 'Invitation personnelle'), ('GCK', 'Converti GCK (séance du soir)'), ('EVANGELISATION', 'Évangélisation'), ('SEANCE', 'Première séance (de passage)'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('SUIVI', 'En cours de suivi'), ('RESTE', "Intégré(e) dans l'église"), ('PARTI', 'Parti(e)')], default='SUIVI', max_length=10)),
                ('observations', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouveaux_venus', to='Eglises.eglise')),
            ],
            options={
                'ordering': ['-date_venue'],
            },
        ),
    ]
